name: My Open Catalogi Workflow

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:              
      - name: Create an Open Catalogi page
        uses: OpenCatalogi/opencatalogi-action@1.0.0
