name: Mijn Open Catalogi Workflow

on:
 push:
  branches:
   - master

permissions:
 contents: write

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Create or Update publiccode.yaml
     uses: OpenCatalogi/publiccode-action@1.1.0
     with:
      opencatalogi: true
