name: My PublicCode Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@1
      - name: Deploy Product Github Page
        uses: OpenCatalogi/productpage-action@1
