name: My PublicCode Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@1.0.0
        with:
          name: "My Codebase"
          description: "This is a sample repository description"
          publiccode: "publiccode.yml"
          gitname: "Open Catalogi bot"
          gitmail: "bot@opencatalogi.nl"
      - name: Deploy Product Github Page
        uses: OpenCatalogi/productpage-action@1.0.0
    
